# raspberry-make
# https://github.com/gswly/raspberry-make
# do not edit this file, add additional content in file "config"

MAKEFILE_NAME := $(word $(words $(MAKEFILE_LIST)),$(MAKEFILE_LIST))

# load config from external file (optional)
-include config

# config default values
BUILD_DIR ?= $(PWD)/build
BASE ?= https://downloads.raspberrypi.org/raspbian_lite/images/raspbian_lite-2019-04-09/2019-04-08-raspbian-stretch-lite.zip
SIZE ?= 2G
HNAME ?= my-rpi
PREUMOUNT_SCRIPT ?=
POSTUMOUNT_SCRIPT ?=

blank :=
define NL

$(blank)
endef

BASEHASH := $$(echo -n '$(BASE)' | sha256sum | head -c 8)
ROOT_START_SECTORS = $$(fdisk -l $(1) | tail -n1 | awk '{print $$2}')
BOOT_START_SECTORS = $$(fdisk -l $(1) | tail -n2 | head -n1 | awk '{print $$2}')
ROOT_LEN_SECTORS = $$(fdisk -l $(1) | tail -n1 | awk '{print $$4}')
BOOT_LEN_SECTORS = $$(fdisk -l $(1) | tail -n2 | head -n1 | awk '{print $$4}')
ROOT_START_BYTES = $$(($(ROOT_START_SECTORS)*512))
BOOT_START_BYTES = $$(($(BOOT_START_SECTORS)*512))
ROOT_LEN_BYTES = $$(($(ROOT_LEN_SECTORS)*512))
BOOT_LEN_BYTES = $$(($(BOOT_LEN_SECTORS)*512))

define PLAYBOOK_RUN
@echo -e "FROM raspberry-make-cur \n\
COPY . ./ \n\
RUN sudo -u pi ANSIBLE_FORCE_COLOR=true /ansible/lib/ld-musl-x86_64.so.1 --library-path=/ansible/lib:/ansible/usr/lib \
	/ansible/usr/bin/python3.6 /ansible/usr/bin/ansible-playbook -i /ansible/inv.ini playbook.yml \n\
RUN rm -rf ./* \n\
" | docker build $(D) -f - -t raspberry-make-cur
endef

define DOCKERFILE
FROM amd64/alpine:3.9
RUN apk add --no-cache \
    make \
    docker \
    e2fsprogs \
    e2fsprogs-extra \
    dosfstools \
    rsync \
    util-linux
ARG MKF
RUN echo "$$MKF" > /Makefile
COPY . /s/
endef

all:
  # build container and enter
	$(eval export DOCKERFILE)
	echo "$$DOCKERFILE" | docker build . -f - --build-arg MKF="$$(cat $(MAKEFILE_NAME))" -t raspberry-make
	$(if $(shell which sudo),sudo ,)modprobe loop
	$(if $(shell which sudo),sudo ,)modprobe vfat
	docker run --rm \
	--cap-add SYS_ADMIN \
	--security-opt apparmor:unconfined \
	--device /dev/loop0 \
	--device /dev/loop1 \
	-v $(BUILD_DIR):/b \
	-v /var/run/docker.sock:/var/run/docker.sock:ro \
	raspberry-make sh -c "cd /s && make -f /Makefile indocker"

indocker:
	@losetup -d /dev/loop0 2>/dev/null || exit 0
	@losetup -d /dev/loop1 2>/dev/null || exit 0
	@rm -rf /b/*

  # download and import only if necessary
ifeq ($(shell docker image inspect raspberry-make-base-$(BASEHASH) >/dev/null 2>&1 || echo 1),1)
  # download
	wget -O /tmp/base.tmp.zip $(BASE)
	cd /tmp && unzip base.tmp.zip
	rm /tmp/base.tmp.zip
	mv /tmp/*img /tmp/base.tmp

  # mount root and boot
	losetup /dev/loop0 /tmp/base.tmp -o $(call ROOT_START_BYTES,/tmp/base.tmp)
	losetup /dev/loop1 /tmp/base.tmp -o $(call BOOT_START_BYTES,/tmp/base.tmp)
	mount /dev/loop0 /mnt
	mount /dev/loop1 /mnt/boot

  # save partition table
	dd if=/tmp/base.tmp of=/mnt/pt bs=1M count=1

  # save files that cannot be edited inside docker
	cp /mnt/etc/hosts /mnt/etc/_hosts
	cp /mnt/etc/resolv.conf /mnt/etc/_resolv.conf
	cp /mnt/etc/mtab /mnt/etc/_mtab

  # import into docker
	tar -C /mnt -c . | docker import - raspberry-make-base-$(BASEHASH)

  # umount
	umount /mnt/boot
	umount /mnt
	losetup -d /dev/loop1
	losetup -d /dev/loop0
	rm /tmp/base.tmp
endif

  # add qemu, check that sudo works correctly. IMPORTANT: keep --credential yes
	docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes >/dev/null
	@echo -e "FROM multiarch/alpine:armhf-v3.9\n\
	FROM raspberry-make-base-$(BASEHASH) \n\
	COPY --from=0 /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static \n\
	RUN sudo -u pi sh -c 'test \$$(id -ru) -eq \$$(id -u) && test \$$(id -u) -eq 1000' \n\
	RUN sudo -u pi sudo sh -c 'test \$$(id -ru) -eq \$$(id -u) && test \$$(id -u) -eq 0' \n\
	" | docker build - -t raspberry-make-cur

  # add ansible, prepare for playbooks
	@echo -e "FROM amd64/alpine:3.9 \n\
	RUN apk add --no-cache ansible \n\
	FROM raspberry-make-cur \n\
	COPY --from=0 / /ansible \n\
	RUN echo 'rpi ansible_connection=local ansible_python_interpreter=/usr/bin/python3' > /ansible/inv.ini \n\
	WORKDIR /playbook \n\
	RUN chown pi:pi /playbook \n\
	" | docker build - -t raspberry-make-cur

  # run playbooks
	$(foreach D,$(shell ls */playbook.yml | xargs -n1 dirname),$(PLAYBOOK_RUN)$(NL))

  # export partition table
	docker run --rm raspberry-make-cur cat /pt | tee /tmp/output.tmp >/dev/null

  # cleanup
	@echo -e "FROM raspberry-make-cur \n\
	RUN rm -rf /playbook /ansible /pt /usr/bin/qemu-arm-static \n\
	" | docker build - -t raspberry-make-cur

  # allocate image, adjust root size, recreate file systems
  # https://github.com/RPi-Distro/pi-gen/blob/30a1528ae13f993291496ac8e73b5ac0a6f82585/export-image/prerun.sh#L58
	truncate -s $(SIZE) /tmp/output.tmp
	printf "d;2;n;p;;$(call ROOT_START_SECTORS,/tmp/output.tmp);;w;" | tr ";" "\n" | fdisk /tmp/output.tmp || exit 0
	losetup /dev/loop0 /tmp/output.tmp -o $(call ROOT_START_BYTES,/tmp/output.tmp) --sizelimit $(call ROOT_LEN_BYTES,/tmp/output.tmp)
	losetup /dev/loop1 /tmp/output.tmp -o $(call BOOT_START_BYTES,/tmp/output.tmp) --sizelimit $(call BOOT_LEN_BYTES,/tmp/output.tmp)
	mkfs.ext4 -L rootfs -O '^huge_file,^metadata_csum,^64bit' /dev/loop0
	mkdosfs -n boot -F 32 /dev/loop1

  # mount
	mount /dev/loop0 /mnt
	mkdir /mnt/boot
	mount /dev/loop1 /mnt/boot

  # export
	@docker container rm raspberry-make-tmp >/dev/null 2>&1 || exit 0
	docker create --name raspberry-make-tmp raspberry-make-cur /bin/exit >/dev/null
	docker export raspberry-make-tmp | tar xf - -C /mnt/
	docker container rm raspberry-make-tmp >/dev/null
	rm /mnt/.dockerenv

  # restore files that cannot be edited inside docker
	rm -f /mnt/etc/hosts && mv /mnt/etc/_hosts /mnt/etc/hosts
	rm -f /mnt/etc/resolv.conf && mv /mnt/etc/_resolv.conf /mnt/etc/resolv.conf
	rm -f /mnt/etc/mtab && mv /mnt/etc/_mtab /mnt/etc/mtab

  # set hostname
	echo $(HNAME) > /mnt/etc/hostname
	sed -i 's/^127\.0\.1\.1.\+$$/127.0.1.1       $(HNAME)/' /mnt/etc/hosts

	$(PREUMOUNT_SCRIPT)

	umount /mnt/boot
	losetup -d /dev/loop1
	umount /mnt
	losetup -d /dev/loop0

	$(POSTUMOUNT_SCRIPT)

	mv /tmp/output.tmp /b/output.img

self-update:
	curl -o $(MAKEFILE_NAME) https://raw.githubusercontent.com/gswly/raspberry-make/master/rpimake.mk
