
- hosts: all
  gather_facts: yes
  tasks:

  - name: timezone
    become: yes
    timezone:
      name: Europe/Paris

  - name: disable_disk_expansion
    become: yes
    replace:
      path: /boot/cmdline.txt
      regexp: 'init=[^ ]+'
      replace: ''

  - name: disable_disk_resize
    become: yes
    shell: update-rc.d resize2fs_once remove && rm /etc/init.d/resize2fs_once

  - name: remove_quiet_flag
    become: yes
    replace:
      path: /boot/cmdline.txt
      regexp: 'quiet ?'
      replace: ''
